apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cj1u1p6xn-python 
  janus-idp.io/tekton: cj1u1p6xn-python
  backstage.io/kubernetes-id: cj1u1p6xn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cj1u1p6xn-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml